spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/memory
    username: postgres
    password: Kada@18july
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
